### ISSUE TITLE
Casting a map into a list<pair> yields incorrect results 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama.old#3563] opened 2022-12-24 03:06 UTC
**Describe the bug**
When I define a parameter concerning a pair with a among facet, the value selected for this parameter is not the right one.

**To Reproduce**
Test the following model:
```
model testAmongPair
global {   
	pair<int,int> resolution <- 640::480 among:  list<pair<int,int>> ([176::144,320::240,640::480]) ;	
	reflex refresh {
		write resolution;
	}
}
experiment display_webcam autorun: true{
	parameter "Possible resolutions" var: resolution ;
}
```

The resolution displayed should be 640::480 but is instead 176::144. 

**Desktop (please complete the following information):**
 - OS: windows 10
 - GAMA version: git 1.9

**Comment by AlexisDrogoul** [comment] 2022-12-24 14:51
The cause of this problem is that the casting of the map `[176::144,320::240,640::480]` into a `list<pair<int,int>>` does not work (it first casts the `map` into a `list`, returning its values, and then casts each of them into a `pair<int,int>`, returning `[144::144,240::240,480::480]`). I've changed the title of the issue accordingly. The workaround before I issue a fix is to use the `pairs` attribute of maps: 
```
pair<int,int> resolution <- 640::480 among:  [176::144,320::240,640::480].pairs ;
```

EDIT: issuing a fix is not so evident, as it would break the logic of the casting -- applying a list<t1> casting operator to a map<k,v> will only apply to the values (and cast each of them to t1). This is why the `pairs` attribute exists in the first place, to specify that one wants explicitly to work on the pairs and not only on the values.

**Comment by AlexisDrogoul** [comment] 2023-01-14 18:02
Given the latest comment, this bug will not be fixed. So let's close the issue report !

**Closed as completed by AlexisDrogoul** 2023-01-14 18:02 UTC
Labels: 😱 Bug, About GAML, 😅 Workaround
