### ISSUE TITLE
Plots show issues in step back

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3548] opened 2022-12-09 12:20 UTC
**Describe the bug**
The plot in the mode `Test - Memorize Experiment - keep_seed.gaml` seems to show issues in the step back function.
Indeed after step back, dots do not match with the previous dots (the ones when steping the simulation).

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git
 - Java version: 17

**Comment by AlexisDrogoul** [comment] 2022-12-12 02:43
Is it related in some way to #3510 ? If yes, would it be possible to address the different issues related to "memorise" or "step back" experiments before we release the 1.9.0 version ?

**Comment by lesquoyb** [comment] 2022-12-12 07:28
To me it's exactly the same issue, if you do it multiple times in a row you will notice that all points will follow the same path, hinting that the problem is just an offset in the beginning when stepping back 
example:
![image](https://user-images.githubusercontent.com/6374469/206985185-33a63368-990c-429e-86ef-94cada867447.png)
here, apart from the first series (in red), the 4 other series all have the same values
Note: if you do not step back up to the first step, there's no problem

**Comment by lesquoyb** [comment] 2022-12-16 03:05
closing as a duplicate of #3510

**Closed as completed by lesquoyb** 2022-12-16 03:05 UTC
