### ISSUE TITLE
Autosave doesn't save images properly with required resolution

### ISSUE THREAD

**Issue by leenr01** [gama-platform/gama.old#3570] opened 2023-01-02 12:26 UTC
**Describe the bug**
When using Autosave with chart and changing the resolution to a higher resolution like {1000,1000} or {2000,2000}, the saved images appear black. 
Another issue is that I cannot use "every" with autosave to specify the frequency of saving a snapshot and change the resolution at the same time. When I add the "every" statement, the images are always saved with the default resolution even if I changed it manually.

**To Reproduce**
1. Go to any model that has charts, for example, prey_predator model 13
2. For any chart, add the faucet "Autosave: {1000,1000}"
3. Run the experiment and see the error in saved snapshots
For the other issue 
2. Add the faucet "Autosave: {1000,1000} every(10#cycles)"
3. Run the experiment and see error in image size.

**Expected behavior**
I need a way to save snapshots at a specific frequency and with high resolution.

**Screenshots**
Sample screenshots for both problems.
![prey_predator_model_display_Population_information_size_256x252_cycle_1_time_1672661099549](https://user-images.githubusercontent.com/120193559/210230659-f3a72adb-373c-4332-b8d1-3414ca207fb4.png)
![prey_predator_model_display_Population_information_size_2000x2000_cycle_155_time_1672661000071](https://user-images.githubusercontent.com/120193559/210230662-57535966-8a29-4ac4-a613-079bcb30d613.png)

**Desktop:**
 - OS: Windows 10
 - GAMA version: 1.8.2

**Additional context**
Is there a way to change the resolution of taking a snapshot manually in the output window (using the camera shortcut on graphs)?

**Comment by AlexisDrogoul** [comment] 2023-01-22 17:14
I've pushed a commit for the first problem (problem is that the JComponent was independently setting the clip based on the view size). 

Regarding the second one, GAML does manifestly not know what to do with an expression like `{1000,1000} every(10#cycles)`. As I understand it, it was interpreting it as `every(container, int)`, returning an empty list... The correct syntax is `every(10#cycles) ? {1000,1000}  : nil`, but actually yours makes sense, so I've committed 1 new operator : an other form of `every` that either return `nil` or the the first operand depending on the value of the cycle (for an `int` operand, it will return 0 or the operand; for a `float` operand, it will return `0.0` or the operand; for a `bool` operand, it will return `false` or the operand). The syntax is the one you used. 

![Image 2023-01-23 00-07-45](https://user-images.githubusercontent.com/579256/213929526-02823d83-48e2-42c8-95f5-d5247954a8c5.png)

**Comment by leenr01** [comment] 2023-01-22 18:39
Dear Alexis,
Thank you very much for your answers.
Is there a way that I can test the fix? Or should I download the alpha version?
I am sorry I am new to this.

**Comment by sriramab** [comment] 2023-01-22 20:01
If you are not at a critical stage of your project, you can try and use the help>update ?

**Comment by leenr01** [comment] 2023-01-23 07:57
I tried that, still, nothing has changed.

**Comment by lesquoyb** [comment] 2023-01-27 09:52
You can try with the latest [alpha release](https://github.com/gama-platform/gama/releases/tag/1.9.0), that fix should be included

**Comment by AlexisDrogoul** [comment] 2023-02-14 09:35
Dear @leenr01, did you succeed in testing the new implementation ?

**Comment by leenr01** [comment] 2023-02-26 13:15
Dear Alexis, Unfortunately no, the image is still not saved correctly with high resolution in the alpha version 1.9.0. Below is an example. Instead of saving this single chart in a large image, I am getting this.
![ants_model_display_Comparison_size_1000x1000_cycle_4_time_1677404307499](https://user-images.githubusercontent.com/120193559/221412642-5d6f854f-1856-4840-8e0d-70f8a6c5a621.png)

The other issue regarding every(10#cycles) is now fixed.

**Comment by AlexisDrogoul** [comment] 2023-03-06 10:46
Hi @leenr01 ,

It's working for me w/o problems on my macOS computer. I suspect there might be something in the configuration of your machine that creates this problem. Or maybe something else. 

In any case, I have written a small test model to verify if we are testing the same thing and how. 
The model is here : https://github.com/gama-platform/gama/blob/777d03beb62fb29a9f53487cd0e2daa3ab4d1b54/msi.gama.core/tests/Basic%20Tests/issues/Issue3570.gaml

Can you test it ? In my case, it produces the right size of image at the right rate... 
![Issue3570_model_display_One chart_size_1000x1000_cycle_400_time_1678099262989](https://user-images.githubusercontent.com/579256/223088625-8b17a634-47cc-41f4-8381-6e859af7f86f.png)

If it is the case for you too, then you face another problem somewhere... 

Cheers
Alexis

**Comment by leenr01** [comment] 2023-03-12 08:45
Dear @AlexisDrogoul
I tried the model on GAMA 1.9.0 on Windows 10 with 64-bit operating system.
I am still not getting the correct results. Please find below the images I am getting.


![Issue3570_model_display_One chart_size_1000x1000_cycle_1_time_1678609780688](https://user-images.githubusercontent.com/120193559/224533630-323d10b0-17a4-41dc-887a-59522807dfca.png)
![Issue3570_model_display_One chart_size_1000x1000_cycle_7_time_1678609785597](https://user-images.githubusercontent.com/120193559/224533634-cda88d2b-f9f8-4cd7-8061-95959f18e9e3.png)
![Issue3570_model_display_One chart_size_1000x1000_cycle_281_time_1678609448092](https://user-images.githubusercontent.com/120193559/224533635-d9c096d8-8931-42c5-ab95-e6085a892f3e.png)

**Comment by AlexisDrogoul** [comment] 2023-03-12 09:07
@ptaillandier @lesquoyb can you try it on Windows 10 ? @RoiArthurB on Linux ?  It is working w/o problems on macOS.

**Comment by lesquoyb** [comment] 2023-03-12 09:17
I can't test right now, but @leenr01's images looks like the problem can be (partially) related to the issue #3557

**Comment by hqnghi88** [comment] 2023-03-12 09:21
This https://github.com/gama-platform/gama/releases/tag/1.9.0 work well on my win 11. It produce right resolution for java2d.
The opengl produce a strange result: png file is 5000x5000 but the chart is small (as Baptiste pointed out) and repeated
![Issue3570_model_display_One chart_size_5000x5000_cycle_2_time_1678612794250](https://user-images.githubusercontent.com/6105384/224535775-6b3617ca-67ef-409f-862d-c4e2f6ed3530.png)

**Comment by lesquoyb** [comment] 2023-03-12 10:23
I had the opportunity to try it on w11, but only with 2d (3d crashes my computer). It does work with the latest release but with two exception:
 * the every statement seems to always return nil (nothing happens if I leave it). I tried to replace it with `#cycle mod 100 = 0 ? {1000, 1000} : nil ` with the same result, maybe #cycle is not reevaluated every step ? 
 * When removing the every statement, the images start to be recorded only starting step 2
Both issues are probably related
Another thing that I'm not sure about is that to me, the texts seem more pixelated in the png than in the original display given the same size on screen:
![image](https://user-images.githubusercontent.com/6374469/224538484-c938bbb4-b991-409d-ad56-dddcddd12d7e.png)
Not sure if it's a bug or something normal, I tried to change the png resolution but it all looks the same

**Comment by hqnghi88** [comment] 2023-03-12 10:45
@lesquoyb you have 10k matrix so open in gama will give that pixelizations effect. If you can zoom to original size it is smooth.

**Comment by AlexisDrogoul** [comment] 2023-03-12 11:40
Yep. The pixelisation comes from the view in GAMA.
Regarding the "every" problem, it's strange. On my setup it works flawlessly ... However, I noticed that you use `#cycle`  (the constant, actually the unit) and not `cycle`, the attribute. 

here is the code of the display i'm using: 

```gaml
		display Population_information refresh: every(5#cycles) autosave: {1000,1000} every 10#cycle {
			chart "Species evolution" type: series size: {1,0.5} position: {0, 0} {
				data "number_of_preys" value: nb_preys color: #blue;
				data "number_of_predator" value: nb_predators color: #red;
			}
			chart "Prey Energy Distribution" type: histogram background: #lightgray size: {0.5,0.5} position: {0, 0.5} {
				data "]0;0.25]" value: prey count (each.energy <= 0.25) color:#blue;
				data "]0.25;0.5]" value: prey count ((each.energy > 0.25) and (each.energy <= 0.5)) color:#blue;
				data "]0.5;0.75]" value: prey count ((each.energy > 0.5) and (each.energy <= 0.75)) color:#blue;
				data "]0.75;1]" value: prey count (each.energy > 0.75) color:#blue;
			}
			chart "Predator Energy Distribution" type: histogram background: #lightgray size: {0.5,0.5} position: {0.5, 0.5} {
				data "]0;0.25]" value: predator count (each.energy <= 0.25) color: #red;
				data "]0.25;0.5]" value: predator count ((each.energy > 0.25) and (each.energy <= 0.5)) color: #red;
				data "]0.5;0.75]" value: predator count ((each.energy > 0.5) and (each.energy <= 0.75)) color: #red;
				data "]0.75;1]" value: predator count (each.energy > 0.75) color: #red;
			}
		}
```

**Comment by lesquoyb** [comment] 2023-03-12 12:17
I'm not sure about the differences you are pointing out, I just copied the model you posted [there](https://github.com/gama-platform/gama/blob/777d03beb62fb29a9f53487cd0e2daa3ab4d1b54/msi.gama.core/tests/Basic%20Tests/issues/Issue3570.gaml) and tried to run it with only changing the type to 2d, and nothing happened.
I really don't understand the difference, so after that I copied the display you posted and paste it in prey predator model 13 and there it works. 
Then I copied those refresh and autosave facets back to the first model, andI got two random snapshots, taken at cycle 450 and 1061:
![image](https://user-images.githubusercontent.com/6374469/224543665-4a84a611-5735-497f-b9c7-3ca78ee403f1.png)
I deleted those snapshots and ran the model again, now I have two other snapshots taken at different cycles again (680 and 1371).
Given that the only noticeable difference in that model is the refresh facet, and the random moment where snapshots were taken, is it possible that it's something related to threads and processing power (it seems that having the rnd processed in the display has a big impact on performance, that's why I can't run in 3d while prey predator works like a charm)?

**Comment by AlexisDrogoul** [comment] 2023-03-12 13:48
Actually make sure the output is synchronised (it should be automatically when snapshots are taken).

The difference I am pointing is that you used #cycle (always equal to 1 as a value) instead of cycle (the attribute of simulations). At least it was the case in the expression you posted.

**Comment by lesquoyb** [comment] 2023-03-13 10:01
Tried with today's release on another computer and I have the same problem, the snapshot is taken but at somewhat random moments.
I tried the two same models as yesterday: https://github.com/gama-platform/gama/blob/777d03beb62fb29a9f53487cd0e2daa3ab4d1b54/msi.gama.core/tests/Basic%20Tests/issues/Issue3570.gaml and predator prey model13.
Same as yesterday, when I remove the "every" statement it seems alright except that I need to execute 2 steps to have the first snapshot

**Comment by AlexisDrogoul** [comment] 2023-03-16 11:08
1) The fact that `every` does not work on your computer is strange to say the least. Can you build a small model that demonstrates it ? (w/o snapshots).

2) The fact that the snapshots are not synchronised with the simulation is also extremely strange. They should be by default. And the simulation should stop while the snapshot is taken. 

Again, I think it would be wise to separate the two issues (for instance close this one and open two new ones)

**Comment by lesquoyb** [comment] 2023-03-20 10:33
Actually, I don't think the `every` is causing any trouble, it's more likely to be related to the fact that snapshots aren't taken every time.

Given the random nature of the bug, And the fact that running the model step by step manual solves it, I think the only issue is a threading problem (snapshot not taken on the main thread for example).

I tried to run the example model on three different windows computer and all had that issue.

For the small problem of the snapshots only starting to be taken at cycle 2, it's pretty simple, it's because of the condition
```
surface.getScope().getClock().getCycle() > 0
```
in LayeredDisplayView.java (line 355)
As that condition is reached before the end of the cycle, for cycle 1 the value is still 0 and thus it doesn't pass it.
What I don't understand though is that the name of the generated file has the correct cycle value while using exactly the same way of accessing it, maybe it's once again something related to threads (the file being created after the whole cycle is done)

**Comment by lesquoyb** [comment] 2023-03-24 07:17
# Summarizing problems
I did some digging, there are five parameters for which I wanted to see the impact on the snapshots :
  * type of display (2d/3d)
  * snapshot optimized setting (true/false)
  * windows scaling ratio (100% or other)
  * if there's another view open next to the display
  * if we resize the snapshot (giving a point as parameter or keeping the display dimensions)

And the two keypoints to check are: 
 * is the image rendered correctly ? (size is correct, everything is in the image, no artifacts....)
 * is it rendered when needed ? (is the snapshot taken at first step, do we have the sync problem ?)

Here is a table summarizing all the possible configurations and results in Windows:
![image](https://user-images.githubusercontent.com/6374469/227450850-b15a4ae0-0e71-4c05-a976-8cae49e61de7.png)
or you can download the xlsx file [here](https://github.com/gama-platform/gama/files/11059412/autosave.xlsx)


 * For the problem "The correct image is in the bottom part of the snapshot[...]" it corresponds to images like this:

![image](https://user-images.githubusercontent.com/6374469/227446240-5c36f306-0c9c-45de-87cd-942909e49a2e.png)

 * "Cycle number in title and content are not sync" typically is when the image is called something_cycle_4_timestamp.png but the content of the image is a few steps behind. Surprisingly, in 2D it was often the opposite: the name was cycle X but the image was cycle X+1
 * "We see a part of the editor in the picture" corresponds to that kind of images: 

![image](https://user-images.githubusercontent.com/6374469/227447211-b8e20995-4196-432c-81b8-c3140b1c77ce.png)
 * "The whole chart is not visible" corresponds to that kind of images (actually all data points are visible, but the graph stops just after the last point instead of leaving some margin):
 
![image](https://user-images.githubusercontent.com/6374469/227447781-b9c440c7-7e9f-4259-a238-445449316ccf.png)

# Remarks 
 * Reloading the experiment seems to solve the first step issue
 * Resizing the view between two snapshots can create the bug with previous snapshots showing up in setups where it was not the case (found with the setup: 3D, no optimization, 100%, another view open, autosave=point(1000,1000))

the model used to generate those data:
```
model Issue3570

global {}

experiment 'Verify me' {
	output synchronized: true { // should be synchronized by default
		display "One chart" 
			autosave: 	//	true
							point(1000,1000) 
			type://	2d
					3d
			{
			
			chart "One series"  {
				data "Data one" value: rnd(100);
				data "Data two" value: rnd(100);
			}
			
		}

	}
}
```
# Analysis
 * The problem with the first step not being saved is present in every setup
 * The only way to get the snapshot to be triggered every cycle and to have the image title and content synced (those two problems certainly have the same root) is to use 2D displays and the snapshot optimization
   * The only way to get a clean image is this setup + scaling ratio of 100%
 * Snapshot optimization + scaling ratio creates an offset on the snapshot
 * Having another view open does not create new problems so if you want to reproduce you can ignore that parameter, though resizing it between two snapshots will create the "The correct image is in the bottom part of the snapshot[...]" issue in some setups
 *  The "The correct image is in the bottom part of the snapshot[...]" issue  (I guess it's the problem encountered by @leenr01) is caused by the setting: 3D display + Scaling ratio != 100% + No snapshot optimization + giving a dimension to autosave
 * "The whole chart is not visible" is cause by the setting: 3D display + Scaling ratio = 100% + No snapshot optimization + giving a dimension to autosave

## Workaround
@leenr01 if you really need to take those snapshots now, you can:
1. switch your display to 2D
2. activate the snapshot optimization in the gama preferences (in Displays -> Presentation and Behavior [...] -> Enable fast snapshots [...])
3. change the windows scale value of your main monitor to 100% 
![image](https://user-images.githubusercontent.com/6374469/227461910-d8c082ba-81ad-447f-9db2-a18b8d8ef899.png)
4. if you need a snapshot of the first step, try to run the experiment a few steps and then reload it

**Comment by AlexisDrogoul** [comment] 2023-03-25 00:55
Hi, @lesquoyb, thanks ! Super useful. 2 quick questions : 

1) In "We see a part of the editor in the picture" : does the image have the correct size, or is the size incorrect too ? 
2) Regarding the "cycle number in title and content are not sync", does it mean that other than that, the picture is correct?

**Comment by lesquoyb** [comment] 2023-03-25 04:12
1. the generated image size is correct with the "We see a part of the editor in the picture" bug
2. Yes the images are correct, they just don't belong to the same cycle as is written in the title (so some threading related problem I guess)

**Comment by AlexisDrogoul** [comment] 2023-03-27 01:38
@gama-platform/committers Can everyone follow the method of @lesquoyb and take snapshots to confirm / infirm his conclusions ? Especially important on other Windows machines (as I can't reproduce a number of them) and Linux ones. 

Thanks !

**Comment by lesquoyb** [comment] 2023-03-27 02:38
Here is a simplified version of the excel file removing useless cases: [autosave.xlsx](https://github.com/gama-platform/gama/files/11074092/autosave.xlsx)

**Comment by LucasGrjs** [comment] 2023-03-27 11:45
Hi, 

Just tested the model prey_predator model 13.gaml with the facet autosave: {1000,1000} and the facet autosave: {1000,1000} every(10#cycles).

Desktop:

    OS: Windows 11
    GAMA version: 1.9.0 (latest Git version)

It work well for java2D display but I have the same issue as @hqnghi88 mentionned for openGL and 3D display

Java2D snapshot : 

![prey_predator_model_display_Population_information_cycle_140_time_1679915808325](https://user-images.githubusercontent.com/55246822/227927857-a229cfcb-49de-4514-a5fd-de775523e91d.png)

![image](https://user-images.githubusercontent.com/55246822/227928060-68086d60-cb40-4e77-952f-c7f54feb4f72.png)

OpenGL/3D snapshot : 

The OpenGL/3D snapshot rendering depends on the actual size of the chart's window at the time to which the snapshot is taken.

Here is some example of snapshots took in the same run of a simulation with different size of chart's window in the application (all of them are 1000x1000)

![image](https://user-images.githubusercontent.com/55246822/227930754-29b239a8-4dbf-4e6e-863f-4f8f76838e1f.png)

![prey_predator_model_display_Population_information_cycle_3_time_1679917093198](https://user-images.githubusercontent.com/55246822/227930924-49bf54f1-0567-4c1c-a120-cf357b3bb5f3.png)

![prey_predator_model_display_Population_information_cycle_4_time_1679917109400](https://user-images.githubusercontent.com/55246822/227930925-7d2908ce-b33b-45da-b360-8f120c1ba48f.png)

![image](https://user-images.githubusercontent.com/55246822/227931507-867397a7-4264-4748-9336-0e8f7b915e44.png)


In all type of display the snapshot at cycle = 1 is not there

**Comment by AlexisDrogoul** [comment] 2023-04-02 01:34
A number of adjustments and bug fixes have been made in the last couple of days regarding the various issues that popped up around this main one. I would tend to think that most of the problems have been addressed, esp. when saving charts at different resolutions. However, @RoiArthurB, would it be possible to make some tests on Linux ? At least four dimensions are needed (like in the Excel file shared by @lesquoyb) : with and without fast snapshot, in 2d or 3d, with only charts or with various elements, at 100% or other scales. Thanks !

**Comment by lesquoyb** [comment] 2023-04-03 04:08
I tried many different setup, and basically apart from the combination of 3d display, snapshot optimization and scaling ratio/second screen everything works fine.

**Closed as completed by lesquoyb** 2023-04-03 04:08 UTC
Labels: 😱 Bug, About GAML, 😅 Workaround, About Charts
