### ISSUE TITLE
[GS] Error message when loading a simulation with malformed parameters is not understandable

### ISSUE THREAD

**Issue by Yapper689** [gama-platform/gama.old#3812] opened 2023-05-10 03:23 UTC
**Describe the bug**

initialize a gaml model
```
received message: {'type': 'UnableToExecuteRequest', 'content': {'exception': 'java.lang.NullPointerException', 'message': 'Cannot invoke "Object.toString()" because the return value of "msi.gama.util.IMap.get(Object)" is null', 'stack': ['msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:118)', 'msi.gama.headless.core.Experiment.setup(Experiment.java:92)', 'msi.gama.headless.job.ManualExperimentJob.loadAndBuildWithJson(ManualExperimentJob.java:138)', 'msi.gama.headless.listener.ServerExperimentController.processUserCommand(ServerExperimentController.java:211)', 'msi.gama.headless.listener.ServerExperimentController.directOpenExperiment(ServerExperimentController.java:322)', 'msi.gama.headless.listener.LoadCommand.launchGamlSimulation(LoadCommand.java:113)', 'msi.gama.headless.listener.LoadCommand.execute(LoadCommand.java:44)', 'msi.gama.headless.listener.LoadCommand.execute(LoadCommand.java:1)', 'msi.gama.headless.listener.CommandExecutor.process(CommandExecutor.java:44)', 'msi.gama.headless.listener.GamaWebSocketServer.onMessage(GamaWebSocketServer.java:226)', 'org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:712)', 'org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)', 'org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)', 'org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)', 'org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)', 'org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)', 'org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)']}, 'command': {'type': 'load', 'model': 'C:\\Stuff\\GAMA\\GamaWorkspace\\Testing7-4\\models\\bug.gaml', 'experiment': 'exp', 'console': True, 'status': True, 'dialog': True, 'runtime': True, 'parameters': [{'type': 'list<int>', 'Closed roads': 'closed_roads', 'value': [1, 2, 3, 4, 5]}]}}
```
**To Reproduce**

Python client
```python
 
import asyncio
from asyncio import Future
from typing import Dict

from gama_client.base_client import GamaBaseClient
from gama_client.command_types import CommandTypes
from gama_client.message_types import MessageTypes


experiment_future: Future
play_future: Future
pause_future: Future
expression_future: Future
step_future: Future
stop_future: Future

async def message_handler(message):
    print("received message:", message)
    if "command" in message:
        if message["command"]["type"] == CommandTypes.Load.value:
            experiment_future.set_result(message)
        elif message["command"]["type"] == CommandTypes.Play.value:
            play_future.set_result(message)
        elif message["command"]["type"] == CommandTypes.Pause.value:
            pause_future.set_result(message)
        elif message["command"]["type"] == CommandTypes.Expression.value:
            expression_future.set_result(message)
        elif message["command"]["type"] == CommandTypes.Step.value:
            step_future.set_result(message)
        elif message["command"]["type"] == CommandTypes.Stop.value:
            stop_future.set_result(message)

async def main():

    global experiment_future
    global play_future
    global pause_future
    global expression_future
    global step_future
    global stop_future
# Experiment and Gama-server constants
    MY_SERVER_URL = "localhost"
    MY_SERVER_PORT = 6868
    GAML_FILE_PATH_ON_SERVER = r"C:\Stuff\GAMA\GamaWorkspace\Testing7-4\models\bug.gaml"
    EXPERIMENT_NAME = "exp"
    current_node = [1,2,3,4,5]
    MY_EXP_INIT_PARAMETERS = [{"type": "list<int>", "Closed roads": "closed_roads", "value": current_node}]


    client = GamaBaseClient(MY_SERVER_URL, MY_SERVER_PORT, message_handler)
    await client.connect()

    print("initialize a gaml model")
    experiment_future = asyncio.get_running_loop().create_future()
    await client.load(GAML_FILE_PATH_ON_SERVER, EXPERIMENT_NAME, True, True, True, True
                      , MY_EXP_INIT_PARAMETERS
                      )
    gama_response = await experiment_future

    try:
        experiment_id = gama_response["content"]
    except Exception as e:
        print("error while initializing", gama_response, e)
        return



if __name__ == "__main__":
    asyncio.run(main())
```

gama model:
```
/**
* Name: bug
* Based on the internal empty template. 
* Author: truon
* Tags: 
*/


model bug

/* Insert your model definition here */

global {
	
		list<int> closed_roads;
}
	


experiment 'exp' type: gui {
	parameter "Closed roads" var: closed_roads <- [1,2,3,4,5,6,7,8,9];
 
}
```

**Comment by lesquoyb** [comment] 2023-05-10 04:25
Ok so turns out the problem is just that the json for parameters was malformed, gama server was unable to find the `name` key. So not a GAMA server bug per se, but I think we can improve the error message

**Comment by lesquoyb** [comment] 2023-08-07 07:44
Should be fixed with the [latest commit](https://github.com/gama-platform/gama/commit/25bfa3f055c117e791eed51030c60a2f8e19d530)

**Closed as completed by lesquoyb** 2023-08-07 07:44 UTC
Labels: 🤗 Enhancement, About Headless, V. 1.9.1
