### ISSUE TITLE
Agent Browser Bug - GAMA 1.8.2

### ISSUE THREAD

**Issue by codorized** [gama-platform/gama.old#3515] opened 2022-10-20 01:40 UTC
**Describe the bug**
Whenever agents of a certain species died during simulation and I'm viewing the Agent Browser of that species afterwards, an error is prompting (See 1st Screenshot - My Model). To verify if this is a generic bug, I run the Predator and Prey model and checked the Prey's Agent Browser and found out that it's having the same problem (See 2nd Screenshot - Predator and Prey). Furthermore, the bug also causes the list of agents in the browser to be empty (See 3rd Screenshot). 

**Expected behavior**
The browser should still display the agents including the ones who died as I believe agents have unique IDs and it would be a great debugging tool. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44542858/196835005-b2ab096d-7951-4d63-8c50-f05b366eca81.png)
![image](https://user-images.githubusercontent.com/44542858/196835028-0f31dba2-886c-4e6e-aeed-1a68cd015e7e.png)
![image](https://user-images.githubusercontent.com/44542858/196835054-2e1772c8-9033-4da8-b696-13b7eb81c3ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: 1.8.2
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment] 2022-10-20 06:59
Sorry, I can't reproduce this. I have launched the Prey Predator model found in the library, let it run for a few cycles to have some preys killed and opened the browser but everything is fine (i.e. the agents are displayed, and no error is launched). 

![screencast 2022-10-20 13-57-11](https://user-images.githubusercontent.com/579256/196877983-f16d81ea-4c1c-4173-85a0-c3f136b1a806.gif)

**Comment by codorized** [comment] 2022-10-20 07:36
Hi Alex,

Here's a video showing how I reproduced the bug. Sorry if it's a bit blurry.  
The model file is: Tutorials -> Predator Prey -> models -> Model 13.gaml

![Bug3](https://user-images.githubusercontent.com/44542858/196885426-0972d0ba-81b3-4658-a95b-cd9be99e9c5f.gif)

**Comment by AlexisDrogoul** [comment] 2022-10-20 08:28
Hi. I've done exactly the same steps and I can't reproduce the bug. Can you send us more information on your configuration ("About GAMA..." then "Installation Details" then "Configuration" then "Copy to Clipboard" and paste here) + ("Preferences..." then "Export to Preferences" and you can copy and paste here the contents of the text file produced) ? Thanks.

**Comment by lesquoyb** [comment] 2022-10-20 08:33
I managed to reproduce the bug, you have to do exactly what @codorized did and open the view with the button on the display's toolbar
![image](https://user-images.githubusercontent.com/6374469/196898430-4d9b459a-fb18-4262-8664-5d70e9f5a4ae.png)
If you open it with the menus on the top of gama everything works as expected.

**Comment by AlexisDrogoul** [comment] 2022-10-20 09:48
This misbehaviour is actually due to a wrong "fix" for #3053 (the fix is not wrong, but the initial request was not correct). I will revert it and hopefully be able to close this one !

**Closed as completed** 2022-11-11 19:04 UTC
Labels: 😱 Bug, About UI, Priority High, 👍 Fix to be tested
