### ISSUE TITLE
Model from tutorial crashes when evaluating an expression on it while running (worked in 1.9.2)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3973] opened 2024-02-19 09:43 UTC
To reproduce

1. Run Gama Server
2. In gama_client.js update your var ABSOLUTE_PATH_TO_GAMA
3. Open Javascript/index.html

Working with Gama 1.9.1 and 1.9.2 but not with 1.9.3 with the following error message when running:

1. ```'gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml'```

````
Image Display Surface created for simulation Simulation 0
Division by zero
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:85)
	at msi.gaml.operators.Maths.opDivide(Maths.java:1079)
	at gaml.additions.core.GamlAdditions.lambda$728(GamlAdditions.java:781)
````

2. ```UD_ReAgent_ABM/ReAgent/models/Gratte_Ciel_Demo.gaml```

`````
java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.topology.ITopology.directionInDegreesTo(msi.gama.runtime.IScope, msi.gama.metamodel.shape.IShape, msi.gama.metamodel.shape.IShape)" because the return value of "msi.gama.runtime.IScope.getTopology()" is null
`````

**Comment by lesquoyb** [comment] 2024-02-19 16:30
Transfering to gama main repo because it seems that the issue is not specific to js client. I managed to reproduce it with the python client under certain circumstances (a certain pause duration between the calls to evaluate the expression `to_geojson(people,"EPSG:4326",["color"])` in `Model 05`).
I'm not even sure it's specific to gama-server and might as well be some kind of threading problem in the core

**Comment by lesquoyb** [comment] 2024-02-19 16:35
update: I can kind of reproduce it in GUI.

- Run the model 05 of road traffic
- while running open the interactive console and execute this line ` to_geojson(people,"EPSG:4326",["color"])`
- See this error:

```
at cycle 7824: The operator goto is not available in the context of Simulation 0
in Simulation 0
in path path_followed <- self.goto(return_path:true, target:the_target, on:the_graph);
```
In the eclipse console I have this message:
```
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:72)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:108)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:87)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:139)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:443)
	at msi.gama.runtime.IScope.execute(IScope.java:414)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:443)
	at msi.gama.runtime.IScope.execute(IScope.java:414)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:443)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:269)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:261)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:240)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:581)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:298)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:238)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:348)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:336)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:547)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:113)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:269)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:261)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:240)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:547)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:111)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "msi.gama.util.path.IPath.getEdgeGeometry()" because "o[0]" is null
	at gaml.additions.core.GamlAdditions.lambda$266(GamlAdditions.java:337)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:101)
	... 37 more
```

**Comment by AlexisDrogoul** [comment] 2024-02-20 01:58
I can't reproduce it (on the GUI version). I've tried different configurations, but no way ... Is there a way to systematically reproduce it ?

**Comment by agrignard** [comment] 2024-02-20 03:10
Using the client approach make it crashes systematically.

To reproduce:

1. run the server from a terminal using this command
```bash gama-headless.sh -socket 6868```

2. Checkout this repo ```https://github.com/gama-platform/gama.clients```

3. In this file https://github.com/gama-platform/gama.clients/blob/main/javascript/js/gama_client.js line 17 modify the path to your local model ```var modelPath```

4. Open https://github.com/gama-platform/gama.clients/blob/main/javascript/index.html on a browser

**Comment by lesquoyb** [comment] 2024-02-20 16:47
As an alternative, here is my python project that also triggers the exception after a few seconds running:
You need to replace gaml_file_path with the path of your own model 05 gaml file
```python
import asyncio
from pathlib import Path
from typing import Dict

from gama_client.sync_client import GamaSyncClient
from gama_client.message_types import MessageTypes


async def async_command_answer_handler(message: Dict):
    print("Here is the answer to an async command: ", message)


async def gama_server_message_handler(message: Dict):
    print("I just received a message from Gama-server and it's not an answer to a command!")
    print("Here it is:", message)


async def main():

    # Experiment and Gama-server constants
    server_url = "localhost"
    server_port = 6868
    gaml_file_path = "D:\gama\msi.gama.models\models\Tutorials\Road Traffic\models\Model 05.gaml"
    exp_name = "road_traffic"
    exp_parameters = [{"type": "int", "name": "nb_preys_init", "value": 100}]

    client = GamaSyncClient(server_url, server_port, async_command_answer_handler, gama_server_message_handler)

    print("connecting to Gama server")
    await client.connect()

    print("initialize a gaml model")
    gama_response = client.sync_load(gaml_file_path, exp_name, True, True, True, True, parameters=exp_parameters)
    try:
        experiment_id = gama_response["content"]
        print("experiment id", experiment_id, gama_response)
    except Exception as e:
        print("error while initializing", gama_response, e)
        return

    print("initialization successful, running the model")
    gama_response = client.sync_play(experiment_id)
    if gama_response["type"] != MessageTypes.CommandExecutedSuccessfully.value:
        print("error while trying to run the experiment", gama_response)
        return

    while True:
        await asyncio.sleep(0.1)
        await client.expression(experiment_id, "to_geojson(people,\"EPSG:4326\",[\"color\"])")


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by AlexisDrogoul** [comment] 2024-02-21 12:34
This is ok for all clients (json, python) in both GUI and headless. Closing !

**Closed as completed by AlexisDrogoul** 2024-02-21 12:34 UTC
