### ISSUE TITLE
Inactive greyed icons incorrectly displayed on Linux

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3460] opened 2022-07-11 05:19 UTC
### Steps to reproduce
1. Run any model

2. Observe the "step" icon (second from the left)

3. When the simulation is run, it becomes gray and blurry (as if its size is doubled).

![Capture d’écran du 2022-07-11 12-13-24](https://user-images.githubusercontent.com/579256/178193730-b6d4c5d4-4aaa-4def-843b-27ebf82f81b0.png)

It happens with other icons as well (back/forward icons in the editor when no text has been entered, "Simulation Perspective Icon" when no experiment is running, etc... 

It seems to be related to the fact that I am running on an HiDPI screen. Can someone test this on "normal" screens ? 

### System and version 
Gama git version, Ubuntu 20.04

**Comment by lesquoyb** [comment] 2022-07-13 08:48
Tried on my laptop: no problem as long as I keep a 100% scaling, if I change to any other value I get the same problem

**Comment by lesquoyb** [comment] 2022-08-08 03:01
I tried the new bug fix, nothing changed on my computer.
In case it can help: I noticed that the icon size is smaller with a scaling of 200%:
![image](https://user-images.githubusercontent.com/6374469/183329833-e232610c-5498-4fdc-a34d-50d86aec67ca.png)
than with a scaling of 125%:
![image](https://user-images.githubusercontent.com/6374469/183329882-c1f23e11-593e-43d1-abd5-76d16c82bc82.png)
 which is the opposite of what I would have expected

**Comment by AlexisDrogoul** [comment] 2022-08-08 10:20
The last commit effectively does not solve the issues in the global toolbar, which is described in the plugin.xml (see the screenshot) and not programmatically -- so all the changes are managed by SWT directly. 

![Image 2022-08-08 17-02-32](https://user-images.githubusercontent.com/579256/183393219-682c1a0c-0bd3-4ca0-bb4f-ccd46d5e8200.png)

This issue is maybe related to this : https://bugs.eclipse.org/bugs/show_bug.cgi?id=568407, which is however marked as solved. Does changing GTK version affect the outcome ? 

The positive point, however, is that the fix seems to solve the editors' toolbars icons, which are managed programmatically in GAMA: before the fix, the "greyed out/disabled" icons where computed automatically by SWT (like in the global toolbar), now they are computed in GamaIcons, indicating that SWT does not take into account the "disabled" icon in the plugin.xml and that the problem is in this "disablement" computation on Linux. This is confirmed by  https://bugs.eclipse.org/bugs/show_bug.cgi?id=575492 that pinpoints exactly the same issue (w/o a fix or a workaround, however).

**Comment by AlexisDrogoul** [comment] 2022-08-21 10:00
Should be tested with the new version of Eclipse (either 2022-06  - https://www.eclipse.org/downloads/packages/release/2022-06/r/eclipse-ide-java-and-dsl-developers - or the upcoming 2022-09 - https://download.eclipse.org/eclipse/downloads/drops4/S-4.25M3-202208171800/ -)

**Comment by RoiArthurB** [comment] 2022-08-22 10:20
@AlexisDrogoul I'm building some GAMA with Eclipse 2022-06, I let you try to see if it fix the issue and doesn't create any new ones : https://github.com/RoiArthurB/GAMA-182-test-builder/actions/runs/2903093404

PS: On my Linux I never saw this issue and can't reproduce it :/

**Comment by AlexisDrogoul** [comment] 2022-09-09 02:41
Problem has been fixed on the SWT side (https://github.com/eclipse-platform/eclipse.platform.swt/pull/327), but it won't be out for 4.25 (Eclipse 2022-09). Should we wait til December ?

**Comment by lesquoyb** [comment] 2022-09-09 03:06
I don't think waiting to try with the next release would be an issue considering that there will still be some work going on until at least October (and the release could be out before December like it was the case for the September release)

**Comment by AlexisDrogoul** [comment] 2022-12-18 09:19
We should build GAMA with 2022-12 now that #3553 is fixed -- and this would remove this issue as well.

**Comment by RoiArthurB** [comment] 2022-12-19 03:55
Fixed with the issue #3553 and the merge of #3544 :)

**Closed as completed by RoiArthurB** 2022-12-19 03:55 UTC
Labels: 😱 Bug, OS Linux, About UI, ❌ Not fixable
