### ISSUE TITLE
Switch Workspace doesn't restart GAMA

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3790] opened 2023-04-22 06:00 UTC
**Describe the bug**
When switching workspace from the UI File->Switch Workspace , if I am not wrong GAMA should restart after changing the workspace. It's not the case on my computer

**To Reproduce**
File->Switch Workspace

**Expected behavior**
Gama should restart alone

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC OS Monterey 
 - 1.9.1 release

**Comment by AlexisDrogoul** [comment] 2023-04-22 06:26
Cant" reproduce it on GAMA 1.9.1 release on macOS Ventura. Both creating a new workspace and using an old workspace make GAMA restart.

**Comment by agrignard** [comment] 2023-04-23 09:30
OK maybe i didn't explain it well. indeed GAMA "restart" the only thing is that the application is not shown as the first one on the screen after the restart , so the app is indeed opened but the user need to go the Gama app to open it. So it's maybe not a big deal and not an issue (or maybe just related to Monterey). What about windows user? . The same behavior is happening when clicking on ```File->Restart GAMA```

**Comment by lesquoyb** [comment] 2023-04-24 11:01
Yes also on Windows the focus is not given to gama when restarting, you can see it in taskbar but if you have another window that was open, this window will cover gama.
I also noticed that this happens for the "select workspace" wizard at normal startup, it gets hidden by the splash screen sometimes, but I'm not able to reproduce it every time.

**Comment by AlexisDrogoul** [comment] 2023-04-29 09:27
Can you both, @lesquoyb @agrignard test if the same behavior happens with Eclipse as well ? Doing the same thing (restarting, switching workspace). Thanks !

**Comment by lesquoyb** [comment] 2023-04-29 11:15
Can't reproduce with eclipse on my personal computer but I can with the work one. Both laptops with no second screen while testing

**Comment by AlexisDrogoul** [comment] 2023-07-22 04:29
It's really a window manager issue and I cant see how GAMA can prevent this to happen. Closing it for now !

**Closed as completed by AlexisDrogoul** 2023-07-22 04:29 UTC
Labels: ❌ Not reproducible
