### ISSUE TITLE
Intermittent exception "Cannot invoke "java.lang.ThreadLocal.get()" because "msi.gaml.expressions.GamlExpressionFactory.parser" is null"

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3625] opened 2023-02-19 08:17 UTC
**Describe the bug**
At least two reports have been made about the appearance of this exception at startup (sometimes preventing GAMA to open), especially when no GAML editor is open. 
It seems that there are some racing conditions that make the plugin `msi.gama.lang.gaml` not opening on time and so not able to initialise the parser before it is needed elsewhere (by another plugin).

**To Reproduce**
Not really easy to spot for the moment. Opening a viewer of a GIS / OSM file, closing GAMA and reopening it can sometimes trigger the exception. 

**Expected behavior**
That no exception appear. 

**Desktop (please complete the following information):**
 - OS: macosX + Windows 11
 - GAMA version: 1.9 dev

**Comment by LucasGrjs** [comment] 2023-02-20 21:09
**Desktop :**
 - OS : Windows 11
 - GAMA version : 1.9.0 dev, 1.8.2 dev, 1.8.2 RC2
 - Eclipse version : Eclipse DSL 2022-03, Eclipse DSL 2022-12

I'm having this issue for the second time now,  I solved it the first time by cleansing all folder related to Eclipse (**.m2, .p2, eclipse-workspace, .eclipse**) and by doing a new installation of Eclipse.

I'm currently having this issue again and I haven't been able to solve it again so here is some info I gathered while trying to solve this issue :

- The issue is not related to GAMA workspace nor Eclipse workspace (both has been cleaned and the bug is still here).
- I tried multiple Eclipse version (**Eclipse DSL 2022-03**, **Eclipse DSL 2022-12**) and tried with a fresh GAMA checkout (**both on 1.8.2 and 1.9.0 branches**)
- This bug also impact GAMA stable version, if you are experiencing this bug while developing GAMA on Eclipse, **all the current and future installation of stable version of GAMA on the computer will be "corrupted"** (GAMA closing right after starting with the exception)
- The bug appeared in my case after killing the execution of gama.runtime.product with the **"terminate" button from Eclipse console** while GAMA was open instead of closing the GAMA's window properly
- GAMA can be run properly when you open a .gaml to start the application


Here is the complete NullPointerException on GAMA start : 

```
java.lang.NullPointerException: Cannot invoke "java.lang.ThreadLocal.get()" because "msi.gaml.expressions.GamlExpressionFactory.parser" is null
	at msi.gaml.expressions.GamlExpressionFactory.getParser(GamlExpressionFactory.java:97)
	at msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:149)
	at msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:99)
	at msi.gaml.descriptions.SymbolDescription.compileExpression(SymbolDescription.java:857)
	at msi.gaml.descriptions.SymbolDescription.lambda$3(SymbolDescription.java:779)
	at msi.gaml.statements.Facets.forEachFacet(Facets.java:373)
	at msi.gaml.statements.Facets.forEachFacetIn(Facets.java:387)
	at msi.gaml.descriptions.SymbolDescription.visitFacets(SymbolDescription.java:245)
	at msi.gaml.descriptions.IDescription.visitFacets(IDescription.java:610)
	at msi.gaml.descriptions.SymbolDescription.validateFacets(SymbolDescription.java:770)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:705)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:1001)
	at msi.gaml.descriptions.SymbolDescription.lambda$4(SymbolDescription.java:1021)
	at msi.gaml.descriptions.TypeDescription.visitChildren(TypeDescription.java:768)
	at msi.gaml.descriptions.SpeciesDescription.visitChildren(SpeciesDescription.java:1054)
	at msi.gaml.descriptions.ModelDescription.visitChildren(ModelDescription.java:481)
	at msi.gaml.descriptions.SymbolDescription.compileChildren(SymbolDescription.java:1020)
	at msi.gaml.descriptions.SymbolDescription.compile(SymbolDescription.java:1007)
	at msi.gaml.compilation.kernel.GamaMetaModel.getAbstractModelSpecies(GamaMetaModel.java:268)
	at msi.gama.kernel.root.PlatformAgent.<init>(PlatformAgent.java:140)
	at msi.gama.runtime.GAMA.getPlatformAgent(GAMA.java:597)
	at msi.gama.runtime.GAMA.getRuntimeScope(GAMA.java:436)
	at msi.gama.util.file.GenericFile.<init>(GenericFile.java:56)
	at msi.gama.common.preferences.GamaPreferenceStore.lambda$8(GamaPreferenceStore.java:576)
	at msi.gama.common.preferences.Pref.getValue(Pref.java:341)
	at msi.gama.application.workbench.ApplicationWorkbenchAdvisor.postStartup(ApplicationWorkbenchAdvisor.java:114)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by AlexisDrogoul** [comment] 2023-02-21 16:40
This problem should now be solved, as I have implemented a solution where the parser is loaded extremely early (even before the GAML artefacts are created).

**Closed as completed** 2023-03-06 02:31 UTC
Labels: 😱 Bug, About GAML, Priority High, 👍 Fix to be tested, V. 1.9.0
