### ISSUE TITLE
GUI dashboard for unit tests crashes when launching test experiments

### ISSUE THREAD

**Issue by michatrautweiler** [gama-platform/gama.old#3951] opened 2023-12-27 16:46 UTC
**Describe the bug**
GUI dashboard for unit tests crashes when launching test experiments

**To Reproduce**
1. Launch Gama Editor, view 'Models'
2. Open 'Test models/Basic Tests/models/Boolean.experiment' (or any other of "type: test")
3. Run experiment 'BooleanTests' from the header ribbon of the file opened
4. Switch to view 'Tests' (with the traffic light symbol)
5. See java exception below. No Gama experiments run anymore, restart of Gama is required to recover. 

**Expected behavior**
"the GUI dashboard for unit tests, showing for each test and even each assert whether it passes or fails. Clicking on the button will display in the GAML editor the code line."

is the expected behaviour according to [documentation](https://gama-platform.org/wiki/Writing_Tests#:~:text=the%20GUI%20dashboard%20for%20unit%20tests%2C%20showing%20for%20each%20test%20and%20even%20each%20assert%20whether%20it%20passes%20or%20fails.%20Clicking%20on%20the%20button%20will%20display%20in%20the%20GAML%20editor%20the%20code%20line).

**Screenshots**
<img width="652" alt="screenshot" src="https://github.com/gama-platform/gama/assets/29101313/b4df82b2-bd40-49ae-9d1f-c924b8ba6fe7">

**Desktop (please complete the following information):**
 - OS: macOS 13.6.3 (22G436)
 - PC Model: iMac Retina 5K, 27-inch, 2017
 - GAMA version: 1.9.2.202309031322	ummisco.gama.application.product incl. eclipse EGit plugin
 - Java version: not sure which one Gama uses, terminal output is
> java version "1.8.0_331"
> Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)

while Gama installation contains (Contents/jdk/Contents/Home/release 

> JAVA_VERSION="17.0.8"

 - Graphics cards / Display system: Radeon Pro 575 4 GB

**Additional context**
might be an issues related to SWT or macOS.
In the 'general toolbar' of the 'simulation perspective', the status is 'Tests over: 6 tests, 6 passed' and the background is green (see screenshot).

Full stacktrace:
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Composite.setLayoutDeferred(boolean)" because the return value of "ummisco.gama.ui.views.ExpandableItemsView.getParentComposite()" is null
	at ummisco.gama.ui.views.ExpandableItemsView.lambda$1(ExpandableItemsView.java:242)
	at ummisco.gama.ui.utils.WorkbenchHelper.run(WorkbenchHelper.java:148)
	at ummisco.gama.ui.views.ExpandableItemsView.reset(ExpandableItemsView.java:241)
	at ummisco.gama.ui.views.TestView.init(TestView.java:82)
	at org.eclipse.ui.part.ViewPart.init(ViewPart.java:113)
	at org.eclipse.ui.internal.ViewReference.initialize(ViewReference.java:129)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:344)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:403)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.subscribeTopicToBeRendered(PartRenderingEngine.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.di.internal.extensions.EventObjectSupplier$DIEventHandler.handleEvent(EventObjectSupplier.java:92)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setToBeRendered(UIElementImpl.java:314)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:655)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:790)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:761)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:683)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:678)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1255)
	at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1247)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1235)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:4229)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4227)
	at ummisco.gama.ui.utils.SwtGui.lambda$0(SwtGui.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by AlexisDrogoul** [comment] 2023-12-29 02:26
Hi,

Thanks for the detailed report. Actually, I cant reproduce it on the recent macOS machines (powered by Apple Silicon chips), but as soon as I can get a hand on an Intel Mac, I will try. As we moved to a more recent version of SWT in the recent builds, can you try to download one of the latest releases and see if the problem persists ? @RoiArthurB, which version of Eclipse/SWT do we use now for building GAMA ? 

Alexis

**Comment by michatrautweiler** [comment] 2023-12-29 11:18
Thanks for your analysis, Alexis!
I've just tried to reproduce the issue with the [1.9.3 alpha release](https://github.com/gama-platform/gama/releases/download/1.9.3/GAMA_1.9.3_MacOS_with_JDK_15.12.23_5d0105f.dmg): 
<img width="525" alt="issue3951-gama193alpha" src="https://github.com/gama-platform/gama/assets/29101313/d0f5d6da-9e96-4c43-a95a-24bbc71891d6">

Works for me. Issues is solved on my environment, GUI is shown and test experiment succeeds. Looks to me like this issue just affects the version of SWT used until Gama 1.9.2 on older macOS versions. 

Let me know if I should close the issue.

**Comment by lesquoyb** [comment] 2023-12-29 14:47
Yes, if you have no problem with 1.9.3 we can consider it as solved, I'm closing the issue. Thank you for your feedback

**Closed as completed by lesquoyb** 2023-12-29 14:47 UTC
Labels: 😱 Bug, OS macOS, About UI
