### ISSUE TITLE
On windows, on second screen contextual icons are not displayed correctly when scaling ratios are different

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3673] opened 2023-03-17 08:41 UTC
**Describe the bug**
When running gama on my second screen, which has a different scaling ratio than my primary screen, all the contextual icons are broken:
![image](https://user-images.githubusercontent.com/6374469/225268508-14927f1b-2b60-4c28-82ef-ea5580ac6287.png)
Normal icons are pixelated and the deactivated ones are darkened more than they should.
If I set the same scaling ratio on both screens everything works fine.
It appears in the release and in the git version.
Eclipse doesn't have that bug so I guess it's avoidable
It's the same with icons in contextual menu when right clicking

**Comment by AlexisDrogoul** [comment] 2023-03-18 02:40
Beware that this behaviour only happens (as far as I can tell from the experiments I conducted on Windows 11) in Eclipse / development mode. When running a release, I cannot reproduce any of this. First image is on a display with 200% zoom

![image](https://user-images.githubusercontent.com/579256/226078580-efe4eaf2-ca42-48c4-8f1f-08b9b4a2b884.png)

Second is after moving it to a display with 100% zoom

![Enregistrement 2023-03-18 093658](https://user-images.githubusercontent.com/579256/226079312-99514f21-86be-4ec6-b417-b52ff1d92ee8.gif)

The scaling of everything appears correct. 

However, conducting the exact same manipulations using the development version (from Eclipse) leads to what you are describing. I therefore propose to close this issue, if you can test it is the same in your case ?

**Comment by lesquoyb** [comment] 2023-03-18 03:16
I just tried again and can confirm it is present on the release too for me.

**Comment by hqnghi88** [comment] 2023-03-18 03:44
@lesquoyb not much hope but can you try again with some trick on win: run as admin, or the hdpi in properties of application

**Comment by AlexisDrogoul** [comment] 2023-03-18 06:22
Yep. I think there is definitely something fishy with your settings @lesquoyb -- things are really running smoothly on my side , and I did not change any per-application setting to achieve it.

**Comment by lesquoyb** [comment] 2023-03-18 07:33
I tried to run it in admin with no difference, also tried to force gama to be run on my nvidia gpu or on my amd chipset, no difference either.
Good to know that it's not something widespread though.

About my setup:
windows 11
integrated amd gpu chipset
dedicated gpu nvidia geforce mx450
I force gama to run on the nvidia gpu to avoid the amd bug with some displays
main screen is 15", 2K resolution, usually using 200% or 150% scaling ratio
my second screens are normal (not high dpi) 1920x1080 monitors with 100% or 150% scaling ratio depending if at work or home
it's connected through usb-c to a hub and then via hdmi

Do you see anything else worth mentioning ?

**Comment by AlexisDrogoul** [comment] 2023-03-18 09:05
Are there any per-app settings you may have set when running older versions of GAMA ?

**Comment by hqnghi88** [comment] 2023-03-18 09:07
change manually gama.exe to something.exe to see anything change?

**Comment by lesquoyb** [comment] 2023-03-18 09:20
There's no special setting that I'm aware of, were you thinking about something in particular ?
I tried changing the name and it didn't change anything

**Comment by hqnghi88** [comment] 2023-03-18 09:28
well nothing on my side,  i tried to change the combination of zoom on both 2 displays: main is amd (asus rog g14), 2nd is samsung fullhd through hdmi. I cant see pixelation with my poor eyes but there is no darken disabled thing. One last thing is the win ver. Could you show yours?
Any way if you have time to specify the exact steps to reproduce, we can consider that as a OS configuration problem?
![image](https://user-images.githubusercontent.com/6105384/226097222-def9ce9c-083b-4473-8ea3-41c2a74944af.png)

**Comment by AlexisDrogoul** [comment] 2023-03-18 09:32
@lesquoyb Can't you specify on Windows the zoom on an individual basis (i.e. such app will zoom, such will not, etc.) ? If not, forget about my comment. But I was thinking about something like this: https://www.windowscentral.com/how-change-high-dpi-settings-classic-apps-windows-10-april-2018-update

**Comment by AlexisDrogoul** [comment] 2023-03-18 15:35
I've tried all the different scales and combinations of the two monitors I have and everything remains fine. Maybe you are hit by this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563923 ? Doesn't seem to be widespread, may be linked with some specific graphics configuration ?

**Comment by lesquoyb** [comment] 2023-03-19 10:08
There's actually a trick in the first link you posted that solved the issue for me: it was to set the `High DPI scaling override` application setting to true.
And not only does it fixes this issue but it also fixes the issue gama-platform/gama#3672,  gama-platform/gama#3671, partially the issue gama-platform/gama2#48 and may help with the issue gama-platform/gama#3674 .
The setting that seems to yield the best results is having the `system` option selected.
So I guess we only need to document this trick in troubleshooting to close this issue and gama-platform/gama#3672.
On the microsoft documentation about this setting they mention the surface pro as prone to that kind of bug, so I guess it only appears with really specific hardware with hidpi + unconventional aspect ratio (16:10 in my case, 3:2 for the surface)

**Comment by AlexisDrogoul** [comment] 2023-03-19 10:15
Cool ! Is there a way to have this setting by default, for instance in the installer ? Or will it break other configurations ?

**Comment by lesquoyb** [comment] 2023-03-19 10:27
I was looking up for that info too, I'll keep you updated. 
I don't know if it'll break something else yet, as far as I've seen everything is working well, but there are so many things that can go wrong without being noticed at first sight.

For info: eclipse doesn't have all those display problems on my configuration and yet doesn't have that option checked by default..

My point of view on this is that for now it doesn't seem to concern many computer, so it's better that we keep a version that we know works for most and explain how to fix those issues in the documentation for the few that may encounter them. So we can **finally** produce a release. And if we find out it's possible to force that setting in the install script, we'll put it in the next alpha in order to have time to test it later

**Comment by hqnghi88** [comment] 2023-03-19 13:34
Hi,
As I experienced the insider version (updates per weeks) there is always a kind of this problems related to the windows cores. I dont know what is the usual for windows users as there is no term of long-term support as in linux (there is just BIG update - with BIG bug or seasoning updates - with random bugs). May be the pro user ( who paid more) have their technical support with these or just goback/wait for the next release. I propose, if you have 2 machines, to test with the latest insider version then.

**Comment by lesquoyb** [comment] 2023-03-20 05:19
I updated the [documentation ](https://gama-platform.org/wiki/next/Troubleshooting#general-display-problems-blurry-icons-strange-experiment-displays-dark-icons-blurry-text-different-appearance-on-second-screen-etc) to talk about this workaround and also added by default this setting in the windows installer script, as it actually also solves other issues.
It should now be solved

**Closed as completed** 2023-03-20 05:19 UTC
Labels: 😱 Bug, OS Windows, About UI, Priority High, ❌ Not reproducible
