### ISSUE TITLE
Bing Map Image Import - Issues when rerun the 2nd time

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.old#3708] opened 2023-04-11 14:27 UTC
**Describe the bug**
GAMA shows errors when rerun the model 'Bing Map Image Import' the 2nd time.

**To Reproduce**
1. Go to 'Library models'
2. Click on 'Data\Data importation'
3. Scroll down to 'BingMap Image Import.gaml'
4. Run the model the first time, it shows the result. 
5. Stop simulation
6. Run the model 2nd time, it show issues.

**Expected behavior**

**Screenshots**
![Uploading import bing.png…]()

![image](https://user-images.githubusercontent.com/11825516/231347923-655e89c2-f98b-409d-90c0-42f22abdfa9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - PC Model: Lenovo
 - GAMA version: Windows 64 zip 1.9
 - Java version: 17
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment] 2023-04-12 15:30
I can't reproduce it. @sriramab can you ?

**Comment by sriramab** [comment] 2023-04-13 00:14
I also cannot reproduce it. But the error message is a "time out" message, so it should be a wifi issue here. 

However note that this issue has been reported incorrectly. It is not the bing map model but it is the mapquest model. Thanks to the full screen screenshot. I checked both models and there is no error on reruns / reloads for either model

**Comment by AlexisDrogoul** [comment] 2023-04-13 01:54
We can close it then. Thanks guys !

**Closed as completed by AlexisDrogoul** 2023-04-13 01:54 UTC
Labels: 😱 Bug, V. 1.9.0
