### ISSUE TITLE
Reproductibility: rnd function doesn't always give the same output for a fixed seed

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3526] opened 2022-11-04 08:20 UTC
**Describe the bug**
Investigating a bug reported on the mailinglist, I managed to reduce the model producing the bug to this:
```
model Minimaltest

global {
	
	file shape_file_buildings <- file("../includes/Shapefiles/bestandsgebaeude_export.shp");
	file shape_file_typologiezonen <- file("../includes/Shapefiles/Typologiezonen.shp");
	
	geometry shape <- envelope(shape_file_typologiezonen);
	matrix<float> share_income <- matrix<float>(csv_file("../includes/csv-data_socio/2021-11-18_V1/share-income_V1.csv",  ",", float, true)); // share of households in neighborhood sorted by income
	
	list<species<households>> income_groups_list <- [households_500_1000, households_1000_1500, households_1500_2000, households_2000_3000, households_3000_4000, households_4000etc];
	map<species<households>,float> share_income_map <- create_map(income_groups_list, list(share_income));
	
	init {
		write rnd(1.0);

		create building from: shape_file_buildings ;

		loop income_group over: income_groups_list { 
			loop i over: range(0,3) { // 4 subgroups a created for each income_group to represent the distribution of the given variables
				create income_group number: share_income_map[income_group] *  62.75 {
					do find_house; //Locate household in a random building.
				}
			}
		}
		

		ask agents of_generic_species households {
			let l <- 1.02 among (self.house.get_neighboring_households());
		}
		write rnd(1.0);
	}
}


species households {

	building house; 
	action find_house {
		self.house <- any (building);
		self.location <- self.house.add_tenant();
	}
}

species building {
	
	point add_tenant {
		return any_location_in(self);
	}
	
	list get_neighboring_households { 
		list neighbors;
		ask closest_to(building, self, 2) {
			neighbors <+ inside(agents of_generic_species(households), self);
		}
		return neighbors;
	}
}



species households_500_1000 parent: households {
	
}

species households_1000_1500 parent: households {
}

species households_1500_2000 parent: households {
	int income <- rnd(1500, 2000);
}

species households_2000_3000 parent: households {	
	int income <- rnd(2000, 3000);
}

species households_3000_4000 parent: households {
	int income <- rnd(3000, 4000);
}

species households_4000etc parent: households {
	int income <- rnd(4000, 10000); // max income / month = 10.000
}


experiment test {
	float seed <- 5.0;
}
```
the include folder is [here includes.zip](https://github.com/gama-platform/gama/files/9936218/includes.zip)
Running that model multiple times results in different values printed by the last `write rnd(1.0)` at the end of the `init`. But it shouldn't as the seed is set manually.

**To Reproduce**
1. load this model
2. run once
3. close
4. run again
5. sometimes you have to repeat run/close 4/5 times to get the error.

It is important to close the experiment to reproduce, because using the reload button results in the expected behaviour.

**Expected behavior**
the last `write` prints the same value everytime

**Additional context**
Running on windows 11 with gama git. Reported with gama-rc2.
If you delete the `income` lines in households subspecies the problem won't appear in the example, but in the original model I managed to remove them and it only made the output more "stable" (different results once every three times instead of everytime) so I don't think it is (only) a problem with inheritance but more some kind of cumulative error. Probably in  the spatial operators.

You can find the original model [here](https://groups.google.com/u/1/g/gama-platform/c/U9ZeePEiOUs)

**Comment by AlexisDrogoul** [comment] 2022-11-04 10:07
Do not forget that there are at least 2 seeds with which modellers have to deal in GAMA. The `seed` of the experiment (the one you are defining) and the `seed` of each simulation. If you move `float seed <- 5.0;` to the init of the model (and not the experiment), you will get the same results over and over as it will represent the seed with which the random number generator of the simulation will be defined. Otherwise, the simulation seed is defined randomly.

**Comment by lesquoyb** [comment] 2022-11-04 10:20
To me there's still something unclear about it because:
1. The first random number of the init is always the same, why would only the last one be affected by the location of the setting of seed?
2. If you run it multiple times you'll notice that the last rnd is not the same every time, but is not purely random either and alternates between two/three different values, why and how is it related to setting seed in the experiment instead of the init ? 
3. If that kind of behavior is considered normal when you set the seed in the experiment, it should probably raise a warning

**Comment by benoitgaudou** [comment] 2022-11-04 10:22
Hi,
A point that is confusing is that, when you try to display the seed of the simulation, e.g.:
```
	init {
		write rnd(1.0);
		write ""+self+" - " + seed;
		write self.seed;
```
you get the value 5.0 (the value given in the experiment). 
So modelers see the same seed in the simulation, but different values in the rnd.

Is ther an issue on the accessed `seed`?

**Comment by AlexisDrogoul** [comment] 2022-11-04 15:07
You're right. There is something fishy here. I cant precisely point at the faulty behaviour (in experiment, in simulation ?), but something is not right. 

EDIT: my bad. We reuse the seed of the experiment if no seed is explicitly defined in a simulation (I remember this behaviour was introduced after a related issue had been raised). So it is normal to have the same seeds in all simulations. However, it doesn't explain why the `rnd(1.0)` function returns different values.

**Comment by AlexisDrogoul** [comment] 2022-11-05 01:47
OK. I think I have isolated the faulty operator. Just needs now to chase the bug in Java. 

If you replace : 

```
	point add_tenant {
		return any_location_in(self);
	}
```

by 

```
	point add_tenant {
		return location;
	}
```

The reproducibility problem is gone.

**Comment by AlexisDrogoul** [comment] 2022-11-05 15:54
Actually, the problem is a bit more complex: it seems that `any_location_in` can return a point which, in some circumstances, will make the `closest_to` operator return a different result or do more operations with random number generation involved. Problem is that these circumstances are obscure for the moment !

**Comment by AlexisDrogoul** [comment] 2022-12-12 17:01
I continue digging this issue, and I can now tell that it is linked with your dataset (the shapefile). Loading another one (e.g. one of the "buildings" shape files we have in the library), or assigning a simple geometry (e.g. a square) to the buildings makes the issue vanish. Still digging where, in that case, a different number of calls to the random number generator is done.... and why !

**Comment by AlexisDrogoul** [comment] 2022-12-16 04:46
Thanks to @ptaillandier, I could push a possible fix for this issue. It was actually a combination of multiple things, but the main cause was that the order of the subspecies inside a species (which appear as attributes) was not stable between different instances of the model, as it depended on a topological ordering of the variables done by JGraphT and thus out of the reach of GAMA. This is why reloading it worked (i.e. the same compiled model was used) but not closing and relaunching it (i.e. a new compilation occurs in that case). This in turn had an incidence on the value of `agents`, so that the order of the agents was not the same between two executions. 
The fact that it only appeared with your dataset remains a mystery though (probably some obscure impacts on the ordering of `HashSet`s and `HashMap`s ...).

**Closed as completed** 2022-12-16 06:34 UTC
Labels: 😱 Bug, Priority High, V. 1.8.2, 👍 Fix to be tested
