### ISSUE TITLE
[1.9.3] Very noticeable slowdown in some OpenGL displays after a few thousands of cycles

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3885] opened 2023-09-21 08:40 UTC
**Describe the bug**
In at least two models : Stairs.gaml and Building Elevation.gaml, the OpenGL display slows down considerably after, more or less, ~24000 and ~1500-4500 cycles, for no apparent reason. See illustration below:

![screencast 2023-09-21 15-32-35](https://github.com/gama-platform/gama/assets/579256/6aacc408-1fa5-4db8-aed2-98104ea4434d)

This does not happen in 2d. This does not seem to happen in GAMA 1.9.2 neither (although I only tested the 1.9.2RC). At least I can't reproduce it. And I only tested on macOS so far. 

**To Reproduce**
Open any of the 2 models (maybe others are also submitted to the same), run it and observe the slowdown (if it happens). The simulation itself does not seem to slow down (or maybe just a little bit). 

**Expected behavior**
No slow downs happening. 

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5.2
 - PC Model: MBP 16" M1
 - GAMA version: git (1.9.3)
 - Java version: Java 17.0.8.1+1
 - Graphics cards / Display system: M1 GPU

**Note**
One major change introduced in 1.9.3 is the replacement of JOGL 2.4RC by JOGL 2.5. Could it be the cause ?

**Comment by hqnghi88** [comment] 2023-09-22 02:34
I tried Building Elevation but there is no slow down afet 10k+ cycles , on Win and Mac OS. any specific gama preferences, though?

**Comment by RoiArthurB** [comment] 2023-09-22 09:49
No problem on Linux with this model.

**Comment by AlexisDrogoul** [comment] 2023-09-23 07:41
Very strange. I tried many different combinations of preferences and still can observe that, either the "slowness" is there from start or that it appears progressively (depending on the models).

**Comment by hqnghi88** [comment] 2023-09-23 11:27
I had the Stairs slowness (as i remembered the balls fall faster than) but it is from beginning of simulation

**Comment by hqnghi88** [comment] 2023-09-23 15:30
I go back some local build and it seems JOGL 2.5 is the cause.

**Comment by AlexisDrogoul** [comment] 2023-09-23 17:16
Well -- I have the slowdown also with JOGL 2.4RC. 😕

**Comment by AlexisDrogoul** [comment] 2023-09-24 00:48
@hqnghi88 at which commit did you notice that the slowdown was not here anymore ?

**Comment by hqnghi88** [comment] 2023-09-24 01:17
This still works well (balls fall fast speed) https://github.com/gama-platform/gama/commit/2cbe4e8d5decc729de1a9d10160009ca94861f7a

**Comment by AlexisDrogoul** [comment] 2023-09-24 01:55
OK. I narrowed it down to 72be343e91c09cfec8840d5398ed1c35ca168f9f (more precisely af4e44ec06d8fab336231ab141ed253bc3be6c0e).  Just need to understand why now...

**Comment by AlexisDrogoul** [comment] 2023-09-24 02:10
The changes in `GamaColor` and `IStatusDisplayer` (the two most obvious suspects) are unfortunately not the causes. This will take some time !

**Comment by AlexisDrogoul** [comment] 2023-09-24 05:18
Ok. The cause is likely this line: https://github.com/gama-platform/gama/commit/af4e44ec06d8fab336231ab141ed253bc3be6c0e#diff-3d452663de67d11d4c1e34ee46bf4e92f576b1fbc3b8854ce0c13555d244b63cL375, which inadvertently forces a synchronisation with SWT in the `postStep()` of experiments. Since the update of OpenGL displays is somehow also in sync with SWT, it produces this effect. Now I will try to see why it is necessary, and how it can be replaced without issues...

**Comment by hqnghi88** [comment] 2023-09-24 06:00
I agree, the Stairs is effectively like synced by default. I wonder for the double-sync when user click on button or by facet.

**Comment by AlexisDrogoul** [comment] 2023-09-24 10:15
Actually, it is synced *with SWT* and not *with the simulation*. So it's a kind of UI sync which is normally not necessary (unless we want the actions of the user in the UI be synced with the frames).

**Comment by hqnghi88** [comment] 2023-09-24 15:52
It is fixed on M1, balls fall at fast speed for Stairs, but on Win 11 it occurs new issue, if i do step by step, very well, but as soon as i play (with or without sync with simulation), gama crash immediatly , no log trace in eclipse, but a dump log only

Dp_Libbulletjme version 15.0.0 initializing

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffed9626536, pid=46040, tid=2440

 JRE version: Java(TM) SE Runtime Environment (17.0.8+9) (build 17.0.8+9-LTS-211)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.8+9-LTS-211, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 C  [atio6axx.dll+0x1416536]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 C:\eclipse\hs_err_pid46040.log

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by AlexisDrogoul** [comment] 2023-09-25 00:05
Hi. I think it is a different issue, probably linked with the binary library. Does it use to work before ?

**Comment by hqnghi88** [comment] 2023-09-25 00:18
Yes,  but i will came back with builds from history to be sure.

**Comment by lesquoyb** [comment] 2023-09-25 03:00
Your problem looks like #3425 do you have and AMD chipset on the computer you tested it ? If so then make sure that gama is not executed on it but 100% on a dedicated GPU

**Comment by hqnghi88** [comment] 2023-09-25 03:05
@lesquoyb i think it is not the same, as it works before. in the issue you mentioned, 3d view is not shown, but in my case, step by step works well, just only when the simulation is played. gama will crash. Anyway, i will verify on my win, later.

**Comment by AlexisDrogoul** [comment] 2023-09-25 03:25
I've tried bumping Libbulletjme to its latest version (https://github.com/stephengold/Libbulletjme) but it seems there is now a problem of update: the world needs to be created and updated in the same thread, which is a bit difficult in GAMA.

**Comment by RoiArthurB** [comment] 2023-09-25 04:48
I don't know if it's related, but, on the latest alpha (c2e0cc20), opengl doesn't work anymore... Here's `Stairs.gaml` :

![image](https://github.com/gama-platform/gama/assets/16764085/d5e7d94f-1bfa-4be1-a14a-459e3180fc64)

And no particular logs:
```
init of Editor for Stairs.gaml
Creating part control of Stairs.gaml
Updating toolbar for Stairs.gaml
Updating toolbar for Stairs.gaml
```

**Comment by AlexisDrogoul** [comment] 2023-09-25 06:29
@RoiArthurB 
1) Did it work just before ? 
2) Does it happen on the dev version as well ? 

In any case, can you open a separate issue with all the elements (exact versions of everything, etc.). Thanks !

**Comment by AlexisDrogoul** [comment] 2023-09-25 09:22
@hqnghi88 can you test with the new libraries and mechanisms for updating the physical world in the same thread I just committed ?

**Comment by hqnghi88** [comment] 2023-09-25 09:32
Quick try give the same result, Stairs crash, bu Perfect Gas Chamber works (as usual before)

**Comment by AlexisDrogoul** [comment] 2023-09-25 09:51
OK. Can you : 

1) comment the lines in `NativeBulletBodyWrapper`:
```
	static {
		CollisionShape.logger.setLevel(Level.OFF);
		NativePhysicsObject.loggerN.setLevel(Level.OFF);
		PhysicsSpace.logger.setLevel(Level.OFF);
		PhysicsCollisionObject.logger.setLevel(Level.OFF);
		PhysicsRigidBody.logger2.setLevel(Level.OFF);
	}
```

2) Launch it again and see if there are any warning in the console (in that case, share them here)
3) Run the "Stairs" model by adding a small delay to the step duration and see if it changes anything

**Comment by hqnghi88** [comment] 2023-09-25 09:58
Dp_Libbulletjme version 18.4.0 initializing
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc6fc0.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc48d0.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc0080.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc21e0.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc5980.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc64a0.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc0610.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc4e60.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc2770.
Sep 25, 2023 4:56:36 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 24121bc5f10.
Key pressed in Newt listener: KeyEvent[EVENT_KEY_PRESSED, code 0x11, sym 0x11, char '
Sep 25, 2023 4:56:46 PM com.jme3.bullet.objects.PhysicsRigidBody rebuildRigidBody
INFO: Created 241259bfc60.
#

And after that is dump core log

**Comment by hqnghi88** [comment] 2023-09-25 10:13
It seems to be a problem of texture rendering. as @lesquoyb recommended, i re-installed newest Adrenaline and all 3D works flawlessly. Sorry @AlexisDrogoul for bother with physic libs.

**Comment by AlexisDrogoul** [comment] 2023-09-25 11:48
So you mean that there aren't any problem with the native physics library ?

**Comment by hqnghi88** [comment] 2023-09-25 11:56
At least with you new strategy, it works perfectly. I will try to test again the history in this issue with and without Adrenaline driver, to confirm.

**Comment by hqnghi88** [comment] 2023-09-25 13:06
I confirm that there is no problem with physics library, the fix works well with https://github.com/gama-platform/gama/commit/ab7b731038dba2f637cd346d1ed9d085cad2d640 . The crash is from my machine configuration.

**Closed as completed** 2023-09-25 13:36 UTC
Labels: 😱 Bug, OS macOS, 🖥 Display OpenGL, Version Git
