### ISSUE TITLE
Some models are only displayed in half

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3448] opened 2022-06-21 07:24 UTC
**Describe the bug**
In some models the display of the simulation only has the left half visible when in tabs. If you go fullscreen and then go back to the tabs view everything goes back to normal.
Here is an example with the model `Comodel Example (Mixed Behaviors).gaml` from Library Models
![half_display_bug](https://user-images.githubusercontent.com/6374469/174739650-ff3086fd-14c9-4764-9cd9-3880073d5257.gif)

For that model another way to fix it is to set the type of display to `opengl`, but I didn't try on others so I don't know if it's always the case.

I encountered that bug in some models I was working on, and sometimes changing a bit the agents (load a different shapefile in my case) would fix it for some reason. I also saw the exact same model (`Comodel Example (Mixed Behaviors).gaml`) having the same bug + a vertical separator displayed in the middle of the screen, but impossible to interact with it.

I'm running gama git on Windows with a radeon integrated chipset. I tried different scaling parameters but it doesn't change anything

**Comment by hqnghi88** [comment] 2022-06-21 09:06
OK (to avoid comodel related) here it is:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6105384/174761625-6aa19e68-ddb4-479f-8dc5-eabf9e9a1a15.png">
it is somehow layout display problem with Grid in java2D. and resize event the display also make it work, not only go in fullscreen mode.

**Comment by AlexisDrogoul** [comment] 2022-06-22 08:49
Can't reproduce it on macOS. What happens if you replace the `grid` layer by a `species` layer ? It seems that the dynamic construction of images (from the grid) might be the problem, but I'm not sure.

**Comment by lesquoyb** [comment] 2022-06-22 11:36
@hqnghi88 Strange, on my computer that one displays normally

**Comment by hqnghi88** [comment] 2022-06-22 16:53
@lesquoyb not the original, you must change the display to java2D.
@AlexisDrogoul the same with species in place of grid
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/6105384/175094314-d575736a-d5af-4f3f-951b-e0dd71577df2.png">

**Comment by hqnghi88** [comment] 2022-06-22 17:03
I tried with different width height for grid. It seems the construction of grid affect the layout. The bigger size of grid, the easier this issue occurs.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/6105384/175096082-b2eecfde-a3de-481f-b201-ac631d40ee3b.png">

**Comment by lesquoyb** [comment] 2022-07-12 03:00
Last commits fixed it for me, can you try it too on your models @hqnghi88 ?
Just to add more informations in case we have related problems: I noticed that the display is still split at the initialization, but then resized, here is what happens precisely when reloading the simulation: ![half_display_bugfix](https://user-images.githubusercontent.com/6374469/178399031-2edd4493-97e2-450f-8ffb-fd261964fe4a.gif)

**Comment by hqnghi88** [comment] 2022-07-12 09:34
It fixed on my side. Thanks

**Closed as completed** 2022-07-12 10:31 UTC
Labels: 😱 Bug, OS Windows, About Models Library, About UI, 📺 Display Java2D, V. 1.8.2, 👍 Fix to be tested
